version: 2.1

aliases:
  make_out_dirs: &make_out_dirs
    run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_WORKSPACE $CIRCLE_TEST_REPORTS/{bitswap}
  restore_gomod: &restore_gomod
    restore_cache:
      keys:
        - go-bitswap-dep-{{ .Branch }}-{{ checksum "~/ipfs/go-bitswap/go.sum" }}-{{ .Environment.CIRCLE_JOB }}
        - go-bitswap-dep-{{ .Branch }}-{{ checksum "~/ipfs/go-bitswap/go.sum" }}-
        - go-bitswap-dep-{{ .Branch }}-
        - go-bitswap-dep--master-
  store_gomod: &store_gomod
      save_cache:
        key: v4-dep-{{ .Branch }}-{{ checksum "~/ipfs/go-ipfs/go.sum" }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - ~/go/pkg/mod
          - ~/.cache/go-build/

commands:
  benchmark:
    parameters:
      output:
        type: string
      branch:
        type: string
        default: HEAD
    steps:
      - checkout
      - run: git checkout << parameters.branch >>
      - *make_out_dirs
      - *restore_gomod
      - run:
          command: go test -run=NONE -bench=. ./... | tee /tmp/circleci-workspace/<< parameters.output >>
          environment:
            IPFS_LOGGING: critical
            CGO_ENABLED: 0
      - persist_to_workspace:
          root: /tmp/circleci-workspace
          paths:
            - << parameters.output >>
      - *store_gomod

defaults: &defaults
  working_directory: ~/ipfs/go-ipfs
  environment:
    GO111MODULE: "on"
    TEST_NO_DOCKER: 1
    TEST_NO_FUSE: 1
    GOPATH: /home/circleci/go
    CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    CIRCLE: 1
    SERVICE: circle-ci
    CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
    CIRCLE_WORKSPACE: /tmp/circleci-workspace
    TEST_VERBOSE: 1
    TRAVIS: 1

jobs:
  gobuild:
    docker:
      - image: circleci/golang:1.12
    <<: *defaults
    steps:
    - checkout
    - *make_out_dirs
    - *restore_gomod
    - run:
        command: bin/build.sh

    - *store_gomod
  benchmark-release:
    docker:
      - image: circleci/golang:1.12
    <<: *defaults
    steps:
      - benchmark:
          output: benchmark-release.txt
          branch: release
  benchmark-before:
    docker:
      - image: circleci/golang:1.12
    <<: *defaults
    steps:
      - benchmark:
          output: benchmark-before.txt
          branch: master
  benchmark-after:
    docker:
      - image: circleci/golang:1.12
    <<: *defaults
    steps:
      - benchmark:
          output: benchmark-after.txt
  benchmark-compare:
    docker:
      - image: circleci/golang:1.12
    <<: *defaults
    steps:
      - checkout
      - *make_out_dirs
      - attach_workspace:
          at: /tmp/circleci-workspace
      - run: bin/diff-benchmarks.sh /tmp/circleci-workspace/benchmark-before.txt /tmp/circleci-workspace/benchmark-after.txt
      - run: bin/diff-benchmarks.sh /tmp/circleci-workspace/benchmark-release.txt /tmp/circleci-workspace/benchmark-after.txt
  
workflows:
  version: 2
  test:
    jobs:
    - gobuild
    - benchmark-before
    - benchmark-after
    - benchmark-release
    - benchmark-compare:
        requires:
          - benchmark-after
          - benchmark-before
          - benchmark-release